server:
  port: 8080
  servlet:
    contextPath: /member

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 20

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 10
      password: ""

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      #      ddl-auto: create
      ddl-auto: update
    open-in-view: false

  security:
    security:
      oauth2:
        client:
          registration:
            kakao:
              client-id: '${kakao.client.id}'
              client-secret: '${kakao.client.secret}'
              client-authentication-method: client_secret_post
              redirect-uri: '${kakao.redirect-url}'
              authorization-grant-type: authorization_code
              client-name: Kakao
              scope:
                - profile_nickname
                - account_email
          provider:
            kakao:
              authorization-uri: https://kauth.kakao.com/oauth/authorize
              token-uri: https://kauth.kakao.com/oauth/token
              user-info-uri: https://kapi.kakao.com/v2/user/me
              user-name-attribute: id
    user:
      name: user
      password: password

  kafka:
    bootstrap-servers: ${KAFKA_CLUSTER_URL}

jwt:
  secret_key: ${jwt.secret_key}
  access-token-validity-in-seconds: 30000
  refresh-token-validity-in-seconds: 86400

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    root: info
    p6spy: off